//
//  StyleKit.h
//  Domicilios.com
//
//  Created by Tiago Mergulhão on 11/10/16.
//  Copyright (c) 2016 Tiago Mergulhão. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* deliveriesTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* locationTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* listViewTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* mapPlaceholderTargets;

// Colors
+ (UIColor*)red;

// Generated Images
+ (UIImage*)imageOfDeliveries;
+ (UIImage*)imageOfLocation;
+ (UIImage*)imageOfListView;
+ (UIImage*)imageOfMapPlaceholder;

@end
